server:
  port: 8080
spring:
  jmx:
    enabled: false
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    redisson:
      config: classpath:redisson.yaml

curator:
  retryCount: 5  #重试次数
  elapsedTimeMs: 5000   #重试间隔时间
  connectString: 127.0.0.1:2181   # zookeeper 地址
  sessionTimeoutMs: 60000  # session超时时间
  connectionTimeoutMs: 5000  # 连接超时时间
